  7%|█████▋                                                                                | 89/1335 [02:44<38:32,  1.86s/it]Traceback (most recent call last):
{'loss': 1.0555, 'grad_norm': 26.655231475830078, 'learning_rate': 1.9986467692505954e-05, 'epoch': 1.0}
  File "D:\Sentiment-Reasoning-Project\training\encoder.py", line 205, in <module>███████████| 69/69 [01:02<00:00,  1.19it/s]
    trainer.train()
  File "C:\Users\OS\AppData\Local\Programs\Python\Python312\Lib\site-packages\transformers\trainer.py", line 2328, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\OS\AppData\Local\Programs\Python\Python312\Lib\site-packages\transformers\trainer.py", line 2788, in _inner_training_loop
    self._maybe_log_save_evaluate(
  File "C:\Users\OS\AppData\Local\Programs\Python\Python312\Lib\site-packages\transformers\trainer.py", line 3227, in _maybe_log_save_evaluate
    metrics = self._evaluate(trial, ignore_keys_for_eval)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\OS\AppData\Local\Programs\Python\Python312\Lib\site-packages\transformers\trainer.py", line 3176, in _evaluate
    metrics = self.evaluate(ignore_keys=ignore_keys_for_eval)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\OS\AppData\Local\Programs\Python\Python312\Lib\site-packages\transformers\trainer.py", line 4469, in evaluate
    output = eval_loop(
             ^^^^^^^^^^
  File "C:\Users\OS\AppData\Local\Programs\Python\Python312\Lib\site-packages\transformers\trainer.py", line 4760, in evaluation_loop
    metrics = self.compute_metrics(
              ^^^^^^^^^^^^^^^^^^^^^
  File "D:\Sentiment-Reasoning-Project\training\encoder.py", line 69, in compute_metrics
    predictions = np.argmax(predictions, axis=1)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\OS\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\_core\fromnumeric.py", line 1341, in argmax
    return _wrapfunc(a, 'argmax', axis=axis, out=out, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\OS\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\_core\fromnumeric.py", line 54, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\OS\AppData\Local\Programs\Python\Python312\Lib\site-packages\numpy\_core\fromnumeric.py", line 42, in _wrapit
    conv = _array_converter(obj)
           ^^^^^^^^^^^^^^^^^^^^^
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (2, 2183) + inhomogeneous part.
